[package]
name = "sourcepawn-cli"
version = "0.1.0"
authors = ["Dreae <dreae@dreae.onl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
